/**
 * Validation bound constants for Zod schemas.
 * These match the Pydantic model constraints in backend/src/worth_it/models.py.
 */

export const VALIDATION = {
  // === Percentage bounds ===
  PCT_MIN: 0,
  PCT_MAX: 100,
  PCT_MAX_GROWTH_FORM: 10,
  PCT_MAX_ROI_FORM: 20,
  PCT_MAX_TARGET_IRR: 200,
  PCT_MAX_REVENUE_GROWTH: 1000,
  PCT_MIN_REVENUE_GROWTH: -100,

  // === Vesting ===
  VESTING_PERIOD_MIN: 1,
  VESTING_PERIOD_MAX: 10,
  VESTING_PERIOD_DEFAULT: 4,
  CLIFF_PERIOD_MIN: 0,
  CLIFF_PERIOD_MAX: 5,
  CLIFF_PERIOD_DEFAULT: 1,
  VESTING_MONTHS_MIN: 0,
  VESTING_MONTHS_MAX: 120,
  VESTING_MONTHS_DEFAULT: 48,
  CLIFF_MONTHS_MIN: 0,
  CLIFF_MONTHS_MAX: 24,
  CLIFF_MONTHS_DEFAULT: 12,

  // === Exit ===
  EXIT_YEAR_MIN: 1,
  EXIT_YEAR_MAX: 20,
  EXIT_YEAR_VC_MAX: 15,
  EXIT_YEAR_SCENARIO_MAX: 20,

  // === Dilution ===
  DILUTION_YEAR_MIN: -10,
  DILUTION_YEAR_MAX: 20,

  // === Monte Carlo ===
  NUM_SIMULATIONS_MIN: 1,
  NUM_SIMULATIONS_MAX: 100_000,

  // === Cap Table ===
  DEFAULT_TOTAL_SHARES: 10_000_000,
  DEFAULT_OPTION_POOL_PCT: 10,

  // === Funding ===
  MATURITY_MONTHS_MIN: 1,
  MATURITY_MONTHS_MAX: 60,
  MATURITY_MONTHS_DEFAULT: 24,
  INTEREST_RATE_DEFAULT: 5,
  LIQUIDATION_MULTIPLIER_MIN: 0,
  LIQUIDATION_MULTIPLIER_MAX: 10,
  LIQUIDATION_MULTIPLIER_DEFAULT: 1,
  PARTICIPATION_CAP_MIN: 1,

  // === Preference Tier ===
  PREFERENCE_SENIORITY_MIN: 1,
  PREFERENCE_MULTIPLIER_MIN: 1,
  PREFERENCE_MULTIPLIER_DEFAULT: 1,

  // === Valuation Calculator ===
  REVENUE_MULTIPLE_MAX: 100,
  REVENUE_GROWTH_MAX: 10,
  DCF_DISCOUNT_MAX: 1,
  TERMINAL_GROWTH_MAX: 1,
  VC_TARGET_RETURN_MIN: 1,
  VC_TARGET_IRR_MAX: 2,
  VC_DILUTION_MAX: 1,
  VC_EXIT_PROBABILITY_DEFAULT: 1,
  VC_DILUTION_DEFAULT: 0,

  // === First Chicago ===
  SCENARIO_NAME_MAX_LENGTH: 50,
  SCENARIOS_MAX_COUNT: 10,
  FIRST_CHICAGO_EXIT_YEAR_MAX: 20,

  // === Berkus Method ===
  BERKUS_CRITERION_MAX: 500_000,
  BERKUS_CRITERION_MIN_ADJ: -500_000,

  // === Scorecard Method ===
  SCORECARD_SCORE_MAX: 2,
  SCORECARD_WEIGHT_MAX: 1,
  SCORECARD_NAME_MAX_LENGTH: 50,

  // === Risk Factor Method ===
  RISK_FACTOR_ADJ_MIN: -500_000,
  RISK_FACTOR_ADJ_MAX: 500_000,
  RISK_FACTOR_NAME_MAX_LENGTH: 50,

  // === DCF Stages (Phase 6) ===
  DCF_STAGE_YEARS_MAX: 20,
  DCF_STAGE_GROWTH_MIN: -0.5,
  DCF_STAGE_GROWTH_MAX: 2.0,
  DCF_STAGE_MARGIN_MIN: -0.5,
  DCF_STAGE_MARGIN_MAX: 0.8,
  ENHANCED_DCF_STAGES_MAX: 5,
  ENHANCED_DCF_DISCOUNT_MAX: 0.5,
  ENHANCED_DCF_TERMINAL_GROWTH_MAX: 0.1,

  // === WACC (Phase 6) ===
  WACC_COST_OF_EQUITY_MAX: 0.5,
  WACC_COST_OF_DEBT_MAX: 0.3,
  WACC_TAX_RATE_MAX: 0.5,

  // === Real Options (Phase 6) ===
  REAL_OPTION_TIME_MAX: 20,
  REAL_OPTION_VOLATILITY_MAX: 1.5,
  REAL_OPTION_RISK_FREE_MAX: 0.2,
} as const;
