#!/usr/bin/env bash
#
# Generate TypeScript/Zod schemas from FastAPI OpenAPI spec.
# This script extracts the OpenAPI JSON from the backend and generates
# type-safe Zod schemas for use in the frontend.
#
# Usage: ./scripts/generate-types.sh
#
# Requirements:
#   - Python with uv (for backend)
#   - Node.js with npm (for frontend, openapi-zod-client)
#   - Perl (for regex replacement in generated files)
#

set -e

# Check for required tools
command -v perl >/dev/null 2>&1 || { echo "Error: perl is required but not installed"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
OPENAPI_FILE="$ROOT_DIR/openapi.json"
GENERATED_FILE="$FRONTEND_DIR/lib/generated/api-schemas.ts"

# Cleanup handler for errors - ensure temp files are removed
TEMP_FILE=""
cleanup() {
    rm -f "$OPENAPI_FILE" 2>/dev/null || true
    [ -n "$TEMP_FILE" ] && rm -f "$TEMP_FILE" 2>/dev/null || true
}
trap cleanup EXIT ERR

echo "🔍 Generating TypeScript schemas from OpenAPI spec..."
echo ""

# Step 1: Extract OpenAPI JSON from FastAPI
echo "📦 Step 1: Extracting OpenAPI spec from FastAPI..."
cd "$BACKEND_DIR"

OPENAPI_OUTPUT="$OPENAPI_FILE" uv run python -c '
import os
import json
from worth_it.api import app

output_path = os.environ["OPENAPI_OUTPUT"]
openapi_spec = app.openapi()
with open(output_path, "w") as f:
    json.dump(openapi_spec, f, indent=2)
print(f"   OpenAPI spec written to {output_path}")
'

# Step 2: Create the generated directory if it doesn't exist
echo "📁 Step 2: Setting up output directory..."
mkdir -p "$FRONTEND_DIR/lib/generated"

# Step 3: Generate Zod schemas using openapi-zod-client
echo "⚙️  Step 3: Generating Zod schemas..."
cd "$FRONTEND_DIR"

npx openapi-zod-client "$OPENAPI_FILE" \
    --output "$GENERATED_FILE" \
    --export-schemas \
    --with-description \
    --with-docs \
    --no-with-alias \
    --api-client-name "generatedApi"

# Step 4: Fix Zod v3 compatibility issues
echo "🔧 Step 4: Fixing Zod v3 compatibility..."
# z.record(schema) needs z.record(z.string(), schema) in Zod v3
# Using perl for cross-platform compatibility
perl -i -pe 's/z\.record\((z\.[^)]+\))\)/z.record(z.string(), $1)/g' "$GENERATED_FILE"

# Step 5: Add header comment to generated file
echo "📝 Step 5: Adding header comment..."
TEMP_FILE="$(mktemp "${TMPDIR:-/tmp}/generate-types.XXXXXX")"
cat > "$TEMP_FILE" << 'HEADER'
/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is automatically generated from the backend OpenAPI spec.
 * To regenerate, run: ./scripts/generate-types.sh
 *
 * Source: backend/src/worth_it/api.py (FastAPI)
 * Generator: openapi-zod-client
 */

HEADER
cat "$GENERATED_FILE" >> "$TEMP_FILE"
mv "$TEMP_FILE" "$GENERATED_FILE"

# Step 6: Format the generated file with prettier
echo "✨ Step 6: Formatting generated file..."
npx prettier --write "$GENERATED_FILE" 2>/dev/null || echo "   (prettier not configured, skipping)"

# Step 7: Clean up
echo "🧹 Step 7: Cleaning up..."
rm -f "$OPENAPI_FILE"

echo ""
echo "✅ Schema generation complete!"
echo "   Generated: $GENERATED_FILE"
echo ""
echo "📚 Next steps:"
echo "   1. Import generated schemas: import { schemas } from '@/lib/generated/api-schemas'"
echo "   2. Use schemas for API validation in your components"
echo ""
